# Single Forward step of RNN cell

In [6]:
import numpy as np

# RNN cell forward
def rnn_step(x, h_prev, Wx, Wh, b):
    return np.tanh(x @ Wx + h_prev @ Wh + b)

x = np.array([[0.2, -0.1, 0.4]])       
h_prev = np.array([[0.05, 0.1, -0.2]])
Wx = np.array([[0.1, -0.2, 0.3],
               [0.4,  0.0, -0.1],
               [-0.3, 0.2, 0.5]])      
Wh = np.array([[0.2, -0.4, 0.1],
               [0.0,  0.3, -0.2],
               [-0.1, 0.5, 0.4]])     
b = np.array([[0.0, 0.1, -0.05]])  

# compute next hidden state
h_next = rnn_step(x, h_prev, Wx, Wh, b)
print("Next Hidden state: \n",np.round(h_next, 6))

Next Hidden state: 
 [[-0.109558  0.049958  0.124353]]


## Forward Propagation in RNN

In [ ]:
import numpy as np

def rnn_forward(xs, h0, Wx, Wh, b):
    h = h0
    hs = []
    for x in xs:
        h = np.tanh(x @ Wx + h @ Wh + b)
        hs.append(h)
    return np.array(hs)

xs = np.array([[0.2, -0.1, 0.4],
               [0.0,  0.3, -0.2],
               [0.1, -0.4, 0.5]])  # (seq_len=3, input_size=3)

h0 = np.zeros((1, 3))  # (1, hidden_size=3)

Wx = np.array([[0.1, -0.2, 0.3],
               [0.4,  0.0, -0.1],
               [-0.3, 0.2, 0.5]])  # (3, 3)

Wh = np.array([[0.2, -0.4, 0.1],
               [0.0,  0.3, -0.2],
               [-0.1, 0.5, 0.4]])  # (3, 3)

b = np.array([[0.0, 0.1, -0.05]])  # (1, 3)

hs = rnn_forward(xs, h0, Wx, Wh, b)
print(np.round(hs, 6))

[[[-0.139092  0.139092  0.216518]]

 [[ 0.129793  0.259548 -0.134304]]

 [[-0.254867  0.137911  0.175512]]]


## LSTM cell

In [ ]:
import numpy as np

def lstm_step(x, h_prev, c_prev, W, b):
    z = np.dot(np.hstack([x, h_prev]), W) + b
    i, f, o, g = np.split(z, 4, axis=1)
    i, f, o = map(lambda a: 1 / (1 + np.exp(-a)), [i, f, o])
    g = np.tanh(g)
    c = f * c_prev + i * g
    h = o * np.tanh(c)
    return h, c

input_size = hidden_size = 3

x = np.random.randn(1, input_size)
h_prev = np.zeros((1, hidden_size))
c_prev = np.zeros((1, hidden_size))

# weight and bias
W = np.random.randn(input_size + hidden_size, 4 * hidden_size) 
b = np.random.randn(1, 4 * hidden_size)                        

# LSTM forward step
h_next, c_next = lstm_step(x, h_prev, c_prev, W, b)
print("Next hidden state:\n", np.round(h_next, 6))
print("Next cell state:\n", np.round(c_next, 6))

Next hidden state:
 [[ 0.004263  0.205317 -0.584533]]
Next cell state:
 [[ 0.07158   0.227186 -0.731632]]
